version: "3.6"

services:
  obp:
    container_name: obp
    image: openbankproject/obp-full:latest
    restart: always
    ports:
     - "8080:8080"
     - "8082:8082"
     - "8081:8081"
    environment:
      OBP_API_HOSTNAME: http://${domain}:8080
      OBP_BASE_URL_API_EXPLORER: http://${domain}:8082
      OBP_WEBUI_API_EXPLORER_URL: http://${domain}:8082
      OBP_BASE_URL_SOCIAL_FINANCE: http://${domain}:8081
      JAVA_TIMEZONE: ${TZ}
    network_mode: "host"